[project]
authors = ["thomashopkins32 <thopkins1@bnl.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AI-Jam"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[host-dependencies]
python = "3.12.*"

[dependencies]
numpy = "*"
matplotlib = "*"
bluesky = "*"
tiled-client = "*"

